service: github-lambda-status-checks

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: robc@theodo.co.uk
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: '*'

functions:
  githubWebhookListener:
    handler: handler.githubWebhookListener
    description: Listens for pull request events and checks titles
    events:
      - http:
          path: webhook
          method: post
          cors: true
  githubBlockedStatus:
    handler: handler.githubBlockedStatus
    description: Blocks production pull requests between 4pm-8am
    events:
      - schedule: cron(00 16 ? * MON-FRI *)
  githubUnblockedStatus:
    handler: handler.githubUnblockedStatus
    description: Unblocks production pull requests between 8am-4pm
    events:
      - schedule: cron(00 08 ? * MON-FRI *)
